package enum

const (
	// USER_STATUS_AVAILABLE 用户状态可用
	USER_STATUS_AVAILABLE = 0
	// USER_STATUS_UNAVAILABLE 用户状态不可用
	USER_STATUS_UNAVAILABLE = 1
	// TAG_STATUS_AVAILABLE 标签状态可用
	TAG_STATUS_AVAILABLE = 0
	// TAG_STATUS_UNAVAILABLE 标签状态不可用
	TAG_STATUS_UNAVAILABLE = 1
	// TEMPLATE_STATUS_AVAILABLE 模版状态可用
	TEMPLATE_STATUS_AVAILABLE = 0
	// TEMPLATE_STATUS_UNAVAILABLE 模版状态不可用
	TEMPLATE_STATUS_UNAVAILABLE = 1
	// RELATION_USER_TAG_AVAILABLE 用户和标签关联可用
	RELATION_USER_TAG_AVAILABLE = 1
	// RELATION_USER_TAG_UNAVAILABLE 用户和标签关联不可用
	RELATION_USER_TAG_UNAVAILABLE = 0
	// RELATION_TEMPLATE_TAG_AVAILABLE 模版和标签关联可用
	RELATION_TEMPLATE_TAG_AVAILABLE = 1
	// RELATION_TEMPLATE_TAG_UNAVAILABLE 模版和标签关联不可用
	RELATION_TEMPLATE_TAG_UNAVAILABLE = 0
)
