servers:
  shutdown-timeout: "30"
  manage-server:
    port: "8083"
  monitor-server:
    port: "8084"

mysql:
  username: "root"
  password: "zhangbin123"
  network: "tcp"
  server: "mysql.zbest.tech"
  port: "13306"
  database: "notify"
  maxopenconns: "100"
  maxidleconns: "16"
  connmaxlifetime: "100"