// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"notify-server/internal/data/ent/predicate"
	"notify-server/internal/data/ent/templatetagrelation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TemplateTagRelationDelete is the builder for deleting a TemplateTagRelation entity.
type TemplateTagRelationDelete struct {
	config
	hooks    []Hook
	mutation *TemplateTagRelationMutation
}

// Where appends a list predicates to the TemplateTagRelationDelete builder.
func (ttrd *TemplateTagRelationDelete) Where(ps ...predicate.TemplateTagRelation) *TemplateTagRelationDelete {
	ttrd.mutation.Where(ps...)
	return ttrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ttrd *TemplateTagRelationDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ttrd.hooks) == 0 {
		affected, err = ttrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TemplateTagRelationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ttrd.mutation = mutation
			affected, err = ttrd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ttrd.hooks) - 1; i >= 0; i-- {
			if ttrd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ttrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ttrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttrd *TemplateTagRelationDelete) ExecX(ctx context.Context) int {
	n, err := ttrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ttrd *TemplateTagRelationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: templatetagrelation.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: templatetagrelation.FieldID,
			},
		},
	}
	if ps := ttrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ttrd.driver, _spec)
}

// TemplateTagRelationDeleteOne is the builder for deleting a single TemplateTagRelation entity.
type TemplateTagRelationDeleteOne struct {
	ttrd *TemplateTagRelationDelete
}

// Exec executes the deletion query.
func (ttrdo *TemplateTagRelationDeleteOne) Exec(ctx context.Context) error {
	n, err := ttrdo.ttrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{templatetagrelation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ttrdo *TemplateTagRelationDeleteOne) ExecX(ctx context.Context) {
	ttrdo.ttrd.ExecX(ctx)
}
