// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"notify-server/internal/data/ent/templatetagrelation"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// TemplateTagRelation is the model entity for the TemplateTagRelation schema.
type TemplateTagRelation struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TemplateTagRelation) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case templatetagrelation.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type TemplateTagRelation", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TemplateTagRelation fields.
func (ttr *TemplateTagRelation) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case templatetagrelation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ttr.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this TemplateTagRelation.
// Note that you need to call TemplateTagRelation.Unwrap() before calling this method if this TemplateTagRelation
// was returned from a transaction, and the transaction was committed or rolled back.
func (ttr *TemplateTagRelation) Update() *TemplateTagRelationUpdateOne {
	return (&TemplateTagRelationClient{config: ttr.config}).UpdateOne(ttr)
}

// Unwrap unwraps the TemplateTagRelation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ttr *TemplateTagRelation) Unwrap() *TemplateTagRelation {
	tx, ok := ttr.config.driver.(*txDriver)
	if !ok {
		panic("ent: TemplateTagRelation is not a transactional entity")
	}
	ttr.config.driver = tx.drv
	return ttr
}

// String implements the fmt.Stringer.
func (ttr *TemplateTagRelation) String() string {
	var builder strings.Builder
	builder.WriteString("TemplateTagRelation(")
	builder.WriteString(fmt.Sprintf("id=%v", ttr.ID))
	builder.WriteByte(')')
	return builder.String()
}

// TemplateTagRelations is a parsable slice of TemplateTagRelation.
type TemplateTagRelations []*TemplateTagRelation

func (ttr TemplateTagRelations) config(cfg config) {
	for _i := range ttr {
		ttr[_i].config = cfg
	}
}
