// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"notify-server/internal/data/ent/predicate"
	"notify-server/internal/data/ent/templatetagrelation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TemplateTagRelationUpdate is the builder for updating TemplateTagRelation entities.
type TemplateTagRelationUpdate struct {
	config
	hooks    []Hook
	mutation *TemplateTagRelationMutation
}

// Where appends a list predicates to the TemplateTagRelationUpdate builder.
func (ttru *TemplateTagRelationUpdate) Where(ps ...predicate.TemplateTagRelation) *TemplateTagRelationUpdate {
	ttru.mutation.Where(ps...)
	return ttru
}

// Mutation returns the TemplateTagRelationMutation object of the builder.
func (ttru *TemplateTagRelationUpdate) Mutation() *TemplateTagRelationMutation {
	return ttru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ttru *TemplateTagRelationUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ttru.hooks) == 0 {
		affected, err = ttru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TemplateTagRelationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ttru.mutation = mutation
			affected, err = ttru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ttru.hooks) - 1; i >= 0; i-- {
			if ttru.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ttru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ttru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ttru *TemplateTagRelationUpdate) SaveX(ctx context.Context) int {
	affected, err := ttru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ttru *TemplateTagRelationUpdate) Exec(ctx context.Context) error {
	_, err := ttru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttru *TemplateTagRelationUpdate) ExecX(ctx context.Context) {
	if err := ttru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ttru *TemplateTagRelationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   templatetagrelation.Table,
			Columns: templatetagrelation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: templatetagrelation.FieldID,
			},
		},
	}
	if ps := ttru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ttru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{templatetagrelation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// TemplateTagRelationUpdateOne is the builder for updating a single TemplateTagRelation entity.
type TemplateTagRelationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TemplateTagRelationMutation
}

// Mutation returns the TemplateTagRelationMutation object of the builder.
func (ttruo *TemplateTagRelationUpdateOne) Mutation() *TemplateTagRelationMutation {
	return ttruo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ttruo *TemplateTagRelationUpdateOne) Select(field string, fields ...string) *TemplateTagRelationUpdateOne {
	ttruo.fields = append([]string{field}, fields...)
	return ttruo
}

// Save executes the query and returns the updated TemplateTagRelation entity.
func (ttruo *TemplateTagRelationUpdateOne) Save(ctx context.Context) (*TemplateTagRelation, error) {
	var (
		err  error
		node *TemplateTagRelation
	)
	if len(ttruo.hooks) == 0 {
		node, err = ttruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TemplateTagRelationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ttruo.mutation = mutation
			node, err = ttruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ttruo.hooks) - 1; i >= 0; i-- {
			if ttruo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ttruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ttruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ttruo *TemplateTagRelationUpdateOne) SaveX(ctx context.Context) *TemplateTagRelation {
	node, err := ttruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ttruo *TemplateTagRelationUpdateOne) Exec(ctx context.Context) error {
	_, err := ttruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttruo *TemplateTagRelationUpdateOne) ExecX(ctx context.Context) {
	if err := ttruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ttruo *TemplateTagRelationUpdateOne) sqlSave(ctx context.Context) (_node *TemplateTagRelation, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   templatetagrelation.Table,
			Columns: templatetagrelation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: templatetagrelation.FieldID,
			},
		},
	}
	id, ok := ttruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing TemplateTagRelation.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := ttruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, templatetagrelation.FieldID)
		for _, f := range fields {
			if !templatetagrelation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != templatetagrelation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ttruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &TemplateTagRelation{config: ttruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ttruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{templatetagrelation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
