// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"notify-server/internal/data/ent/predicate"
	"notify-server/internal/data/ent/templatetagrelation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TemplateTagRelationQuery is the builder for querying TemplateTagRelation entities.
type TemplateTagRelationQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TemplateTagRelation
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TemplateTagRelationQuery builder.
func (ttrq *TemplateTagRelationQuery) Where(ps ...predicate.TemplateTagRelation) *TemplateTagRelationQuery {
	ttrq.predicates = append(ttrq.predicates, ps...)
	return ttrq
}

// Limit adds a limit step to the query.
func (ttrq *TemplateTagRelationQuery) Limit(limit int) *TemplateTagRelationQuery {
	ttrq.limit = &limit
	return ttrq
}

// Offset adds an offset step to the query.
func (ttrq *TemplateTagRelationQuery) Offset(offset int) *TemplateTagRelationQuery {
	ttrq.offset = &offset
	return ttrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ttrq *TemplateTagRelationQuery) Unique(unique bool) *TemplateTagRelationQuery {
	ttrq.unique = &unique
	return ttrq
}

// Order adds an order step to the query.
func (ttrq *TemplateTagRelationQuery) Order(o ...OrderFunc) *TemplateTagRelationQuery {
	ttrq.order = append(ttrq.order, o...)
	return ttrq
}

// First returns the first TemplateTagRelation entity from the query.
// Returns a *NotFoundError when no TemplateTagRelation was found.
func (ttrq *TemplateTagRelationQuery) First(ctx context.Context) (*TemplateTagRelation, error) {
	nodes, err := ttrq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{templatetagrelation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ttrq *TemplateTagRelationQuery) FirstX(ctx context.Context) *TemplateTagRelation {
	node, err := ttrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TemplateTagRelation ID from the query.
// Returns a *NotFoundError when no TemplateTagRelation ID was found.
func (ttrq *TemplateTagRelationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ttrq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{templatetagrelation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ttrq *TemplateTagRelationQuery) FirstIDX(ctx context.Context) int {
	id, err := ttrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TemplateTagRelation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one TemplateTagRelation entity is not found.
// Returns a *NotFoundError when no TemplateTagRelation entities are found.
func (ttrq *TemplateTagRelationQuery) Only(ctx context.Context) (*TemplateTagRelation, error) {
	nodes, err := ttrq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{templatetagrelation.Label}
	default:
		return nil, &NotSingularError{templatetagrelation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ttrq *TemplateTagRelationQuery) OnlyX(ctx context.Context) *TemplateTagRelation {
	node, err := ttrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TemplateTagRelation ID in the query.
// Returns a *NotSingularError when exactly one TemplateTagRelation ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ttrq *TemplateTagRelationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ttrq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{templatetagrelation.Label}
	default:
		err = &NotSingularError{templatetagrelation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ttrq *TemplateTagRelationQuery) OnlyIDX(ctx context.Context) int {
	id, err := ttrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TemplateTagRelations.
func (ttrq *TemplateTagRelationQuery) All(ctx context.Context) ([]*TemplateTagRelation, error) {
	if err := ttrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ttrq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ttrq *TemplateTagRelationQuery) AllX(ctx context.Context) []*TemplateTagRelation {
	nodes, err := ttrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TemplateTagRelation IDs.
func (ttrq *TemplateTagRelationQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ttrq.Select(templatetagrelation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ttrq *TemplateTagRelationQuery) IDsX(ctx context.Context) []int {
	ids, err := ttrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ttrq *TemplateTagRelationQuery) Count(ctx context.Context) (int, error) {
	if err := ttrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ttrq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ttrq *TemplateTagRelationQuery) CountX(ctx context.Context) int {
	count, err := ttrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ttrq *TemplateTagRelationQuery) Exist(ctx context.Context) (bool, error) {
	if err := ttrq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ttrq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ttrq *TemplateTagRelationQuery) ExistX(ctx context.Context) bool {
	exist, err := ttrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TemplateTagRelationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ttrq *TemplateTagRelationQuery) Clone() *TemplateTagRelationQuery {
	if ttrq == nil {
		return nil
	}
	return &TemplateTagRelationQuery{
		config:     ttrq.config,
		limit:      ttrq.limit,
		offset:     ttrq.offset,
		order:      append([]OrderFunc{}, ttrq.order...),
		predicates: append([]predicate.TemplateTagRelation{}, ttrq.predicates...),
		// clone intermediate query.
		sql:  ttrq.sql.Clone(),
		path: ttrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (ttrq *TemplateTagRelationQuery) GroupBy(field string, fields ...string) *TemplateTagRelationGroupBy {
	group := &TemplateTagRelationGroupBy{config: ttrq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ttrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ttrq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (ttrq *TemplateTagRelationQuery) Select(fields ...string) *TemplateTagRelationSelect {
	ttrq.fields = append(ttrq.fields, fields...)
	return &TemplateTagRelationSelect{TemplateTagRelationQuery: ttrq}
}

func (ttrq *TemplateTagRelationQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ttrq.fields {
		if !templatetagrelation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ttrq.path != nil {
		prev, err := ttrq.path(ctx)
		if err != nil {
			return err
		}
		ttrq.sql = prev
	}
	return nil
}

func (ttrq *TemplateTagRelationQuery) sqlAll(ctx context.Context) ([]*TemplateTagRelation, error) {
	var (
		nodes = []*TemplateTagRelation{}
		_spec = ttrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TemplateTagRelation{config: ttrq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ttrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ttrq *TemplateTagRelationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ttrq.querySpec()
	return sqlgraph.CountNodes(ctx, ttrq.driver, _spec)
}

func (ttrq *TemplateTagRelationQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ttrq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ttrq *TemplateTagRelationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   templatetagrelation.Table,
			Columns: templatetagrelation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: templatetagrelation.FieldID,
			},
		},
		From:   ttrq.sql,
		Unique: true,
	}
	if unique := ttrq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ttrq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, templatetagrelation.FieldID)
		for i := range fields {
			if fields[i] != templatetagrelation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ttrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ttrq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ttrq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ttrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ttrq *TemplateTagRelationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ttrq.driver.Dialect())
	t1 := builder.Table(templatetagrelation.Table)
	columns := ttrq.fields
	if len(columns) == 0 {
		columns = templatetagrelation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ttrq.sql != nil {
		selector = ttrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range ttrq.predicates {
		p(selector)
	}
	for _, p := range ttrq.order {
		p(selector)
	}
	if offset := ttrq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ttrq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TemplateTagRelationGroupBy is the group-by builder for TemplateTagRelation entities.
type TemplateTagRelationGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ttrgb *TemplateTagRelationGroupBy) Aggregate(fns ...AggregateFunc) *TemplateTagRelationGroupBy {
	ttrgb.fns = append(ttrgb.fns, fns...)
	return ttrgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ttrgb *TemplateTagRelationGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ttrgb.path(ctx)
	if err != nil {
		return err
	}
	ttrgb.sql = query
	return ttrgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ttrgb *TemplateTagRelationGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ttrgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ttrgb *TemplateTagRelationGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ttrgb.fields) > 1 {
		return nil, errors.New("ent: TemplateTagRelationGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ttrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ttrgb *TemplateTagRelationGroupBy) StringsX(ctx context.Context) []string {
	v, err := ttrgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ttrgb *TemplateTagRelationGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ttrgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{templatetagrelation.Label}
	default:
		err = fmt.Errorf("ent: TemplateTagRelationGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ttrgb *TemplateTagRelationGroupBy) StringX(ctx context.Context) string {
	v, err := ttrgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ttrgb *TemplateTagRelationGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ttrgb.fields) > 1 {
		return nil, errors.New("ent: TemplateTagRelationGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ttrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ttrgb *TemplateTagRelationGroupBy) IntsX(ctx context.Context) []int {
	v, err := ttrgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ttrgb *TemplateTagRelationGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ttrgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{templatetagrelation.Label}
	default:
		err = fmt.Errorf("ent: TemplateTagRelationGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ttrgb *TemplateTagRelationGroupBy) IntX(ctx context.Context) int {
	v, err := ttrgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ttrgb *TemplateTagRelationGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ttrgb.fields) > 1 {
		return nil, errors.New("ent: TemplateTagRelationGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ttrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ttrgb *TemplateTagRelationGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ttrgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ttrgb *TemplateTagRelationGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ttrgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{templatetagrelation.Label}
	default:
		err = fmt.Errorf("ent: TemplateTagRelationGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ttrgb *TemplateTagRelationGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ttrgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ttrgb *TemplateTagRelationGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ttrgb.fields) > 1 {
		return nil, errors.New("ent: TemplateTagRelationGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ttrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ttrgb *TemplateTagRelationGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ttrgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ttrgb *TemplateTagRelationGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ttrgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{templatetagrelation.Label}
	default:
		err = fmt.Errorf("ent: TemplateTagRelationGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ttrgb *TemplateTagRelationGroupBy) BoolX(ctx context.Context) bool {
	v, err := ttrgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ttrgb *TemplateTagRelationGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ttrgb.fields {
		if !templatetagrelation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ttrgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ttrgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ttrgb *TemplateTagRelationGroupBy) sqlQuery() *sql.Selector {
	selector := ttrgb.sql.Select()
	aggregation := make([]string, 0, len(ttrgb.fns))
	for _, fn := range ttrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ttrgb.fields)+len(ttrgb.fns))
		for _, f := range ttrgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ttrgb.fields...)...)
}

// TemplateTagRelationSelect is the builder for selecting fields of TemplateTagRelation entities.
type TemplateTagRelationSelect struct {
	*TemplateTagRelationQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ttrs *TemplateTagRelationSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ttrs.prepareQuery(ctx); err != nil {
		return err
	}
	ttrs.sql = ttrs.TemplateTagRelationQuery.sqlQuery(ctx)
	return ttrs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ttrs *TemplateTagRelationSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ttrs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ttrs *TemplateTagRelationSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ttrs.fields) > 1 {
		return nil, errors.New("ent: TemplateTagRelationSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ttrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ttrs *TemplateTagRelationSelect) StringsX(ctx context.Context) []string {
	v, err := ttrs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ttrs *TemplateTagRelationSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ttrs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{templatetagrelation.Label}
	default:
		err = fmt.Errorf("ent: TemplateTagRelationSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ttrs *TemplateTagRelationSelect) StringX(ctx context.Context) string {
	v, err := ttrs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ttrs *TemplateTagRelationSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ttrs.fields) > 1 {
		return nil, errors.New("ent: TemplateTagRelationSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ttrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ttrs *TemplateTagRelationSelect) IntsX(ctx context.Context) []int {
	v, err := ttrs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ttrs *TemplateTagRelationSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ttrs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{templatetagrelation.Label}
	default:
		err = fmt.Errorf("ent: TemplateTagRelationSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ttrs *TemplateTagRelationSelect) IntX(ctx context.Context) int {
	v, err := ttrs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ttrs *TemplateTagRelationSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ttrs.fields) > 1 {
		return nil, errors.New("ent: TemplateTagRelationSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ttrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ttrs *TemplateTagRelationSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ttrs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ttrs *TemplateTagRelationSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ttrs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{templatetagrelation.Label}
	default:
		err = fmt.Errorf("ent: TemplateTagRelationSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ttrs *TemplateTagRelationSelect) Float64X(ctx context.Context) float64 {
	v, err := ttrs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ttrs *TemplateTagRelationSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ttrs.fields) > 1 {
		return nil, errors.New("ent: TemplateTagRelationSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ttrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ttrs *TemplateTagRelationSelect) BoolsX(ctx context.Context) []bool {
	v, err := ttrs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ttrs *TemplateTagRelationSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ttrs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{templatetagrelation.Label}
	default:
		err = fmt.Errorf("ent: TemplateTagRelationSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ttrs *TemplateTagRelationSelect) BoolX(ctx context.Context) bool {
	v, err := ttrs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ttrs *TemplateTagRelationSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ttrs.sql.Query()
	if err := ttrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
