// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"notify-server/internal/data/ent/templatetagrelation"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TemplateTagRelationCreate is the builder for creating a TemplateTagRelation entity.
type TemplateTagRelationCreate struct {
	config
	mutation *TemplateTagRelationMutation
	hooks    []Hook
}

// Mutation returns the TemplateTagRelationMutation object of the builder.
func (ttrc *TemplateTagRelationCreate) Mutation() *TemplateTagRelationMutation {
	return ttrc.mutation
}

// Save creates the TemplateTagRelation in the database.
func (ttrc *TemplateTagRelationCreate) Save(ctx context.Context) (*TemplateTagRelation, error) {
	var (
		err  error
		node *TemplateTagRelation
	)
	if len(ttrc.hooks) == 0 {
		if err = ttrc.check(); err != nil {
			return nil, err
		}
		node, err = ttrc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TemplateTagRelationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ttrc.check(); err != nil {
				return nil, err
			}
			ttrc.mutation = mutation
			if node, err = ttrc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ttrc.hooks) - 1; i >= 0; i-- {
			if ttrc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ttrc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ttrc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ttrc *TemplateTagRelationCreate) SaveX(ctx context.Context) *TemplateTagRelation {
	v, err := ttrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ttrc *TemplateTagRelationCreate) Exec(ctx context.Context) error {
	_, err := ttrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttrc *TemplateTagRelationCreate) ExecX(ctx context.Context) {
	if err := ttrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ttrc *TemplateTagRelationCreate) check() error {
	return nil
}

func (ttrc *TemplateTagRelationCreate) sqlSave(ctx context.Context) (*TemplateTagRelation, error) {
	_node, _spec := ttrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ttrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ttrc *TemplateTagRelationCreate) createSpec() (*TemplateTagRelation, *sqlgraph.CreateSpec) {
	var (
		_node = &TemplateTagRelation{config: ttrc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: templatetagrelation.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: templatetagrelation.FieldID,
			},
		}
	)
	return _node, _spec
}

// TemplateTagRelationCreateBulk is the builder for creating many TemplateTagRelation entities in bulk.
type TemplateTagRelationCreateBulk struct {
	config
	builders []*TemplateTagRelationCreate
}

// Save creates the TemplateTagRelation entities in the database.
func (ttrcb *TemplateTagRelationCreateBulk) Save(ctx context.Context) ([]*TemplateTagRelation, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ttrcb.builders))
	nodes := make([]*TemplateTagRelation, len(ttrcb.builders))
	mutators := make([]Mutator, len(ttrcb.builders))
	for i := range ttrcb.builders {
		func(i int, root context.Context) {
			builder := ttrcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TemplateTagRelationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ttrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ttrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ttrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ttrcb *TemplateTagRelationCreateBulk) SaveX(ctx context.Context) []*TemplateTagRelation {
	v, err := ttrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ttrcb *TemplateTagRelationCreateBulk) Exec(ctx context.Context) error {
	_, err := ttrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttrcb *TemplateTagRelationCreateBulk) ExecX(ctx context.Context) {
	if err := ttrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
