// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"notify-server/internal/data/ent/predicate"
	"notify-server/internal/data/ent/usertagrelation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserTagRelationDelete is the builder for deleting a UserTagRelation entity.
type UserTagRelationDelete struct {
	config
	hooks    []Hook
	mutation *UserTagRelationMutation
}

// Where appends a list predicates to the UserTagRelationDelete builder.
func (utrd *UserTagRelationDelete) Where(ps ...predicate.UserTagRelation) *UserTagRelationDelete {
	utrd.mutation.Where(ps...)
	return utrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (utrd *UserTagRelationDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(utrd.hooks) == 0 {
		affected, err = utrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserTagRelationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			utrd.mutation = mutation
			affected, err = utrd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(utrd.hooks) - 1; i >= 0; i-- {
			if utrd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = utrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, utrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (utrd *UserTagRelationDelete) ExecX(ctx context.Context) int {
	n, err := utrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (utrd *UserTagRelationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: usertagrelation.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usertagrelation.FieldID,
			},
		},
	}
	if ps := utrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, utrd.driver, _spec)
}

// UserTagRelationDeleteOne is the builder for deleting a single UserTagRelation entity.
type UserTagRelationDeleteOne struct {
	utrd *UserTagRelationDelete
}

// Exec executes the deletion query.
func (utrdo *UserTagRelationDeleteOne) Exec(ctx context.Context) error {
	n, err := utrdo.utrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usertagrelation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (utrdo *UserTagRelationDeleteOne) ExecX(ctx context.Context) {
	utrdo.utrd.ExecX(ctx)
}
