// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"notify-server/internal/data/ent/predicate"
	"notify-server/internal/data/ent/usertagrelation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserTagRelationQuery is the builder for querying UserTagRelation entities.
type UserTagRelationQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserTagRelation
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserTagRelationQuery builder.
func (utrq *UserTagRelationQuery) Where(ps ...predicate.UserTagRelation) *UserTagRelationQuery {
	utrq.predicates = append(utrq.predicates, ps...)
	return utrq
}

// Limit adds a limit step to the query.
func (utrq *UserTagRelationQuery) Limit(limit int) *UserTagRelationQuery {
	utrq.limit = &limit
	return utrq
}

// Offset adds an offset step to the query.
func (utrq *UserTagRelationQuery) Offset(offset int) *UserTagRelationQuery {
	utrq.offset = &offset
	return utrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (utrq *UserTagRelationQuery) Unique(unique bool) *UserTagRelationQuery {
	utrq.unique = &unique
	return utrq
}

// Order adds an order step to the query.
func (utrq *UserTagRelationQuery) Order(o ...OrderFunc) *UserTagRelationQuery {
	utrq.order = append(utrq.order, o...)
	return utrq
}

// First returns the first UserTagRelation entity from the query.
// Returns a *NotFoundError when no UserTagRelation was found.
func (utrq *UserTagRelationQuery) First(ctx context.Context) (*UserTagRelation, error) {
	nodes, err := utrq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usertagrelation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (utrq *UserTagRelationQuery) FirstX(ctx context.Context) *UserTagRelation {
	node, err := utrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserTagRelation ID from the query.
// Returns a *NotFoundError when no UserTagRelation ID was found.
func (utrq *UserTagRelationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = utrq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usertagrelation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (utrq *UserTagRelationQuery) FirstIDX(ctx context.Context) int {
	id, err := utrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserTagRelation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one UserTagRelation entity is not found.
// Returns a *NotFoundError when no UserTagRelation entities are found.
func (utrq *UserTagRelationQuery) Only(ctx context.Context) (*UserTagRelation, error) {
	nodes, err := utrq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usertagrelation.Label}
	default:
		return nil, &NotSingularError{usertagrelation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (utrq *UserTagRelationQuery) OnlyX(ctx context.Context) *UserTagRelation {
	node, err := utrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserTagRelation ID in the query.
// Returns a *NotSingularError when exactly one UserTagRelation ID is not found.
// Returns a *NotFoundError when no entities are found.
func (utrq *UserTagRelationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = utrq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usertagrelation.Label}
	default:
		err = &NotSingularError{usertagrelation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (utrq *UserTagRelationQuery) OnlyIDX(ctx context.Context) int {
	id, err := utrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserTagRelations.
func (utrq *UserTagRelationQuery) All(ctx context.Context) ([]*UserTagRelation, error) {
	if err := utrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return utrq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (utrq *UserTagRelationQuery) AllX(ctx context.Context) []*UserTagRelation {
	nodes, err := utrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserTagRelation IDs.
func (utrq *UserTagRelationQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := utrq.Select(usertagrelation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (utrq *UserTagRelationQuery) IDsX(ctx context.Context) []int {
	ids, err := utrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (utrq *UserTagRelationQuery) Count(ctx context.Context) (int, error) {
	if err := utrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return utrq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (utrq *UserTagRelationQuery) CountX(ctx context.Context) int {
	count, err := utrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (utrq *UserTagRelationQuery) Exist(ctx context.Context) (bool, error) {
	if err := utrq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return utrq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (utrq *UserTagRelationQuery) ExistX(ctx context.Context) bool {
	exist, err := utrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserTagRelationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (utrq *UserTagRelationQuery) Clone() *UserTagRelationQuery {
	if utrq == nil {
		return nil
	}
	return &UserTagRelationQuery{
		config:     utrq.config,
		limit:      utrq.limit,
		offset:     utrq.offset,
		order:      append([]OrderFunc{}, utrq.order...),
		predicates: append([]predicate.UserTagRelation{}, utrq.predicates...),
		// clone intermediate query.
		sql:  utrq.sql.Clone(),
		path: utrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (utrq *UserTagRelationQuery) GroupBy(field string, fields ...string) *UserTagRelationGroupBy {
	group := &UserTagRelationGroupBy{config: utrq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := utrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return utrq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (utrq *UserTagRelationQuery) Select(fields ...string) *UserTagRelationSelect {
	utrq.fields = append(utrq.fields, fields...)
	return &UserTagRelationSelect{UserTagRelationQuery: utrq}
}

func (utrq *UserTagRelationQuery) prepareQuery(ctx context.Context) error {
	for _, f := range utrq.fields {
		if !usertagrelation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if utrq.path != nil {
		prev, err := utrq.path(ctx)
		if err != nil {
			return err
		}
		utrq.sql = prev
	}
	return nil
}

func (utrq *UserTagRelationQuery) sqlAll(ctx context.Context) ([]*UserTagRelation, error) {
	var (
		nodes = []*UserTagRelation{}
		_spec = utrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UserTagRelation{config: utrq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, utrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (utrq *UserTagRelationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := utrq.querySpec()
	return sqlgraph.CountNodes(ctx, utrq.driver, _spec)
}

func (utrq *UserTagRelationQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := utrq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (utrq *UserTagRelationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usertagrelation.Table,
			Columns: usertagrelation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usertagrelation.FieldID,
			},
		},
		From:   utrq.sql,
		Unique: true,
	}
	if unique := utrq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := utrq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usertagrelation.FieldID)
		for i := range fields {
			if fields[i] != usertagrelation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := utrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := utrq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := utrq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := utrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (utrq *UserTagRelationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(utrq.driver.Dialect())
	t1 := builder.Table(usertagrelation.Table)
	columns := utrq.fields
	if len(columns) == 0 {
		columns = usertagrelation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if utrq.sql != nil {
		selector = utrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range utrq.predicates {
		p(selector)
	}
	for _, p := range utrq.order {
		p(selector)
	}
	if offset := utrq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := utrq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserTagRelationGroupBy is the group-by builder for UserTagRelation entities.
type UserTagRelationGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (utrgb *UserTagRelationGroupBy) Aggregate(fns ...AggregateFunc) *UserTagRelationGroupBy {
	utrgb.fns = append(utrgb.fns, fns...)
	return utrgb
}

// Scan applies the group-by query and scans the result into the given value.
func (utrgb *UserTagRelationGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := utrgb.path(ctx)
	if err != nil {
		return err
	}
	utrgb.sql = query
	return utrgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (utrgb *UserTagRelationGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := utrgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (utrgb *UserTagRelationGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(utrgb.fields) > 1 {
		return nil, errors.New("ent: UserTagRelationGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := utrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (utrgb *UserTagRelationGroupBy) StringsX(ctx context.Context) []string {
	v, err := utrgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (utrgb *UserTagRelationGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = utrgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertagrelation.Label}
	default:
		err = fmt.Errorf("ent: UserTagRelationGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (utrgb *UserTagRelationGroupBy) StringX(ctx context.Context) string {
	v, err := utrgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (utrgb *UserTagRelationGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(utrgb.fields) > 1 {
		return nil, errors.New("ent: UserTagRelationGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := utrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (utrgb *UserTagRelationGroupBy) IntsX(ctx context.Context) []int {
	v, err := utrgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (utrgb *UserTagRelationGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = utrgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertagrelation.Label}
	default:
		err = fmt.Errorf("ent: UserTagRelationGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (utrgb *UserTagRelationGroupBy) IntX(ctx context.Context) int {
	v, err := utrgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (utrgb *UserTagRelationGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(utrgb.fields) > 1 {
		return nil, errors.New("ent: UserTagRelationGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := utrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (utrgb *UserTagRelationGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := utrgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (utrgb *UserTagRelationGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = utrgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertagrelation.Label}
	default:
		err = fmt.Errorf("ent: UserTagRelationGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (utrgb *UserTagRelationGroupBy) Float64X(ctx context.Context) float64 {
	v, err := utrgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (utrgb *UserTagRelationGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(utrgb.fields) > 1 {
		return nil, errors.New("ent: UserTagRelationGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := utrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (utrgb *UserTagRelationGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := utrgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (utrgb *UserTagRelationGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = utrgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertagrelation.Label}
	default:
		err = fmt.Errorf("ent: UserTagRelationGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (utrgb *UserTagRelationGroupBy) BoolX(ctx context.Context) bool {
	v, err := utrgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (utrgb *UserTagRelationGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range utrgb.fields {
		if !usertagrelation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := utrgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := utrgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (utrgb *UserTagRelationGroupBy) sqlQuery() *sql.Selector {
	selector := utrgb.sql.Select()
	aggregation := make([]string, 0, len(utrgb.fns))
	for _, fn := range utrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(utrgb.fields)+len(utrgb.fns))
		for _, f := range utrgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(utrgb.fields...)...)
}

// UserTagRelationSelect is the builder for selecting fields of UserTagRelation entities.
type UserTagRelationSelect struct {
	*UserTagRelationQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (utrs *UserTagRelationSelect) Scan(ctx context.Context, v interface{}) error {
	if err := utrs.prepareQuery(ctx); err != nil {
		return err
	}
	utrs.sql = utrs.UserTagRelationQuery.sqlQuery(ctx)
	return utrs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (utrs *UserTagRelationSelect) ScanX(ctx context.Context, v interface{}) {
	if err := utrs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (utrs *UserTagRelationSelect) Strings(ctx context.Context) ([]string, error) {
	if len(utrs.fields) > 1 {
		return nil, errors.New("ent: UserTagRelationSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := utrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (utrs *UserTagRelationSelect) StringsX(ctx context.Context) []string {
	v, err := utrs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (utrs *UserTagRelationSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = utrs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertagrelation.Label}
	default:
		err = fmt.Errorf("ent: UserTagRelationSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (utrs *UserTagRelationSelect) StringX(ctx context.Context) string {
	v, err := utrs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (utrs *UserTagRelationSelect) Ints(ctx context.Context) ([]int, error) {
	if len(utrs.fields) > 1 {
		return nil, errors.New("ent: UserTagRelationSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := utrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (utrs *UserTagRelationSelect) IntsX(ctx context.Context) []int {
	v, err := utrs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (utrs *UserTagRelationSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = utrs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertagrelation.Label}
	default:
		err = fmt.Errorf("ent: UserTagRelationSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (utrs *UserTagRelationSelect) IntX(ctx context.Context) int {
	v, err := utrs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (utrs *UserTagRelationSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(utrs.fields) > 1 {
		return nil, errors.New("ent: UserTagRelationSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := utrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (utrs *UserTagRelationSelect) Float64sX(ctx context.Context) []float64 {
	v, err := utrs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (utrs *UserTagRelationSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = utrs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertagrelation.Label}
	default:
		err = fmt.Errorf("ent: UserTagRelationSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (utrs *UserTagRelationSelect) Float64X(ctx context.Context) float64 {
	v, err := utrs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (utrs *UserTagRelationSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(utrs.fields) > 1 {
		return nil, errors.New("ent: UserTagRelationSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := utrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (utrs *UserTagRelationSelect) BoolsX(ctx context.Context) []bool {
	v, err := utrs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (utrs *UserTagRelationSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = utrs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertagrelation.Label}
	default:
		err = fmt.Errorf("ent: UserTagRelationSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (utrs *UserTagRelationSelect) BoolX(ctx context.Context) bool {
	v, err := utrs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (utrs *UserTagRelationSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := utrs.sql.Query()
	if err := utrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
