// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"notify-server/internal/data/ent/predicate"
	"notify-server/internal/data/ent/usertagrelation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserTagRelationUpdate is the builder for updating UserTagRelation entities.
type UserTagRelationUpdate struct {
	config
	hooks    []Hook
	mutation *UserTagRelationMutation
}

// Where appends a list predicates to the UserTagRelationUpdate builder.
func (utru *UserTagRelationUpdate) Where(ps ...predicate.UserTagRelation) *UserTagRelationUpdate {
	utru.mutation.Where(ps...)
	return utru
}

// Mutation returns the UserTagRelationMutation object of the builder.
func (utru *UserTagRelationUpdate) Mutation() *UserTagRelationMutation {
	return utru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (utru *UserTagRelationUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(utru.hooks) == 0 {
		affected, err = utru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserTagRelationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			utru.mutation = mutation
			affected, err = utru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(utru.hooks) - 1; i >= 0; i-- {
			if utru.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = utru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, utru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (utru *UserTagRelationUpdate) SaveX(ctx context.Context) int {
	affected, err := utru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (utru *UserTagRelationUpdate) Exec(ctx context.Context) error {
	_, err := utru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (utru *UserTagRelationUpdate) ExecX(ctx context.Context) {
	if err := utru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (utru *UserTagRelationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usertagrelation.Table,
			Columns: usertagrelation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usertagrelation.FieldID,
			},
		},
	}
	if ps := utru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, utru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertagrelation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// UserTagRelationUpdateOne is the builder for updating a single UserTagRelation entity.
type UserTagRelationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserTagRelationMutation
}

// Mutation returns the UserTagRelationMutation object of the builder.
func (utruo *UserTagRelationUpdateOne) Mutation() *UserTagRelationMutation {
	return utruo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (utruo *UserTagRelationUpdateOne) Select(field string, fields ...string) *UserTagRelationUpdateOne {
	utruo.fields = append([]string{field}, fields...)
	return utruo
}

// Save executes the query and returns the updated UserTagRelation entity.
func (utruo *UserTagRelationUpdateOne) Save(ctx context.Context) (*UserTagRelation, error) {
	var (
		err  error
		node *UserTagRelation
	)
	if len(utruo.hooks) == 0 {
		node, err = utruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserTagRelationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			utruo.mutation = mutation
			node, err = utruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(utruo.hooks) - 1; i >= 0; i-- {
			if utruo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = utruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, utruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (utruo *UserTagRelationUpdateOne) SaveX(ctx context.Context) *UserTagRelation {
	node, err := utruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (utruo *UserTagRelationUpdateOne) Exec(ctx context.Context) error {
	_, err := utruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (utruo *UserTagRelationUpdateOne) ExecX(ctx context.Context) {
	if err := utruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (utruo *UserTagRelationUpdateOne) sqlSave(ctx context.Context) (_node *UserTagRelation, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usertagrelation.Table,
			Columns: usertagrelation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usertagrelation.FieldID,
			},
		},
	}
	id, ok := utruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing UserTagRelation.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := utruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usertagrelation.FieldID)
		for _, f := range fields {
			if !usertagrelation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usertagrelation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := utruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &UserTagRelation{config: utruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, utruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertagrelation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
