// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"notify-server/internal/data/ent/usertagrelation"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// UserTagRelation is the model entity for the UserTagRelation schema.
type UserTagRelation struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserTagRelation) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case usertagrelation.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type UserTagRelation", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserTagRelation fields.
func (utr *UserTagRelation) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usertagrelation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			utr.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this UserTagRelation.
// Note that you need to call UserTagRelation.Unwrap() before calling this method if this UserTagRelation
// was returned from a transaction, and the transaction was committed or rolled back.
func (utr *UserTagRelation) Update() *UserTagRelationUpdateOne {
	return (&UserTagRelationClient{config: utr.config}).UpdateOne(utr)
}

// Unwrap unwraps the UserTagRelation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (utr *UserTagRelation) Unwrap() *UserTagRelation {
	tx, ok := utr.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserTagRelation is not a transactional entity")
	}
	utr.config.driver = tx.drv
	return utr
}

// String implements the fmt.Stringer.
func (utr *UserTagRelation) String() string {
	var builder strings.Builder
	builder.WriteString("UserTagRelation(")
	builder.WriteString(fmt.Sprintf("id=%v", utr.ID))
	builder.WriteByte(')')
	return builder.String()
}

// UserTagRelations is a parsable slice of UserTagRelation.
type UserTagRelations []*UserTagRelation

func (utr UserTagRelations) config(cfg config) {
	for _i := range utr {
		utr[_i].config = cfg
	}
}
