// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NotifyTagColumns holds the columns for the "notify_tag" table.
	NotifyTagColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "desc", Type: field.TypeString, Size: 300},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "status", Type: field.TypeInt, Default: 1},
	}
	// NotifyTagTable holds the schema information for the "notify_tag" table.
	NotifyTagTable = &schema.Table{
		Name:       "notify_tag",
		Columns:    NotifyTagColumns,
		PrimaryKey: []*schema.Column{NotifyTagColumns[0]},
	}
	// NotifyTemplateColumns holds the columns for the "notify_template" table.
	NotifyTemplateColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "desc", Type: field.TypeString, Size: 300},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "content", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt, Default: 1},
	}
	// NotifyTemplateTable holds the schema information for the "notify_template" table.
	NotifyTemplateTable = &schema.Table{
		Name:       "notify_template",
		Columns:    NotifyTemplateColumns,
		PrimaryKey: []*schema.Column{NotifyTemplateColumns[0]},
	}
	// TemplateTagRelationsColumns holds the columns for the "template_tag_relations" table.
	TemplateTagRelationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "template_uuid", Type: field.TypeString, Nullable: true},
		{Name: "tag_uuid", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeInt, Default: 1},
	}
	// TemplateTagRelationsTable holds the schema information for the "template_tag_relations" table.
	TemplateTagRelationsTable = &schema.Table{
		Name:       "template_tag_relations",
		Columns:    TemplateTagRelationsColumns,
		PrimaryKey: []*schema.Column{TemplateTagRelationsColumns[0]},
	}
	// NotifyUserColumns holds the columns for the "notify_user" table.
	NotifyUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "mobile", Type: field.TypeString, Size: 11},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "email", Type: field.TypeString, Size: 100},
		{Name: "status", Type: field.TypeInt, Default: 0},
	}
	// NotifyUserTable holds the schema information for the "notify_user" table.
	NotifyUserTable = &schema.Table{
		Name:       "notify_user",
		Columns:    NotifyUserColumns,
		PrimaryKey: []*schema.Column{NotifyUserColumns[0]},
	}
	// UserTagRelationsColumns holds the columns for the "user_tag_relations" table.
	UserTagRelationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "user_uuid", Type: field.TypeString, Nullable: true},
		{Name: "tag_uuid", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeInt, Default: 1},
	}
	// UserTagRelationsTable holds the schema information for the "user_tag_relations" table.
	UserTagRelationsTable = &schema.Table{
		Name:       "user_tag_relations",
		Columns:    UserTagRelationsColumns,
		PrimaryKey: []*schema.Column{UserTagRelationsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NotifyTagTable,
		NotifyTemplateTable,
		TemplateTagRelationsTable,
		NotifyUserTable,
		UserTagRelationsTable,
	}
)

func init() {
	NotifyTagTable.Annotation = &entsql.Annotation{
		Table: "notify_tag",
	}
	NotifyTemplateTable.Annotation = &entsql.Annotation{
		Table: "notify_template",
	}
	NotifyUserTable.Annotation = &entsql.Annotation{
		Table: "notify_user",
	}
}
