// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Template is the predicate function for template builders.
type Template func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
